In [3]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [63]:
data = pd.read_csv('[raw]transaction.csv')
data.reset_index()

,index,0,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,isFraud
0,0,-42230.193526,-5101.387638,-1039.578439,-4103.881762,-481.492325,153.949065,-2178.036774,-891.009271,953.369683,...,-88.750933,-11.592762,-52.032407,-25.672369,-111.543361,-210.697974,73.541176,-172.315299,296.483322,0
1,1,-42209.877926,-5117.633510,-1397.821642,6962.889312,-1924.489988,-158.493196,498.311517,209.627591,-812.354041,...,-208.061186,-124.940344,79.172531,86.257638,-7.848315,-249.334615,35.663609,224.009132,-217.710221,0
2,2,-42236.157674,-5129.815276,-1398.873663,5004.767253,-2400.486226,-238.530158,90.567017,-329.109034,296.504155,...,-47.719311,-71.998705,62.420910,62.768082,-88.036515,-598.502412,36.833896,189.789615,-223.859055,0
3,3,-42221.757393,-5119.656464,1311.218680,-8376.615388,-1214.086369,1055.847664,175.172740,1745.724502,-742.665168,...,-159.458427,-150.638554,-371.615513,512.300614,-481.414274,186.305790,478.836406,-27.261581,-26.438503,0
4,4,36736.188237,163639.777560,679.947831,6236.709523,8014.720332,911.780585,-1660.033270,-305.826517,-161.577681,...,744.754047,-103.154103,-209.519609,-33.596360,-207.259325,100.974552,194.139818,17.059122,160.992347,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,590535,-42231.474383,-5104.078630,-1274.631753,3234.327481,-1206.473727,120.439451,-2131.793755,-916.454823,1041.127038,...,27.249886,73.623863,-42.620235,-56.606488,-73.753107,-66.875096,8.244650,56.766580,-0.178434,0
590536,590536,-42232.830315,-5127.018736,-1287.192105,-740.210969,-1760.171250,-245.642985,123.576767,-304.617601,139.959572,...,-177.656099,-96.977505,104.087176,93.408999,207.498790,553.706430,-3.405390,63.599074,-199.000255,0
590537,590537,-42232.875921,-5126.700730,-1257.544099,-2325.958728,-1606.860045,-249.087295,118.058963,-313.730362,135.258671,...,-178.595705,-95.909918,103.892064,92.610309,211.778603,552.399719,-1.559262,69.225974,-201.534538,0
590538,590538,-42245.327811,-5132.755788,689.944902,1824.181151,-2742.705782,1020.110236,-301.450964,1641.559412,18.512517,...,157.336505,-549.915673,83.044412,196.371897,23.857307,-35.854012,179.851388,-163.598281,-119.884284,0
590539,590539,-42236.218958,-5128.429684,-824.911277,-5349.448048,-1479.231222,-51.495901,242.172460,-236.708319,388.281990,...,-232.699602,57.291378,-225.949478,-380.634939,342.310697,660.699009,29.038061,-247.751100,450.860744,0

In [64]:
x_data = data.drop('isFraud', axis=1)
y_data = data[['isFraud']]

In [65]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=777, stratify=y_data)

In [66]:
train = pd.concat([x_train, y_train], axis=1)
train.reset_index(drop=True, inplace=True)
x_test.reset_index(drop=True, inplace=True)

In [67]:
train.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,isFraud
0,174374.804838,-12475.639482,1978.004554,-7858.336409,5860.578862,418.165027,2039.108219,159.570096,-242.212834,1596.383278,...,-1394.257696,-289.636228,453.684983,821.086199,2636.392671,-977.774801,2177.022045,112.507737,632.875351,0
1,-42237.786369,-5131.472138,-1237.648009,-3622.854851,-1668.179397,-270.150760,256.747529,-272.211165,188.974681,585.924714,...,26.887746,128.178083,-102.644548,-67.560555,160.836015,945.405393,22.586531,-124.852812,8.086937,0
2,-42238.277055,-5130.050216,-1169.819592,-7170.612139,-1302.887832,-264.308243,99.555085,-357.913080,274.775981,528.681077,...,113.209034,96.867562,-47.541805,7.439499,59.078415,12.554626,59.963048,554.387400,-563.189949,0
3,-42239.799375,-5132.294991,-1072.170872,-666.272834,-2029.560427,-138.083309,177.160271,-102.286180,252.744281,600.572972,...,138.513434,8.598018,-96.529878,-2.794887,-52.789669,31.934902,53.264587,-4.850536,-107.697347,0
4,-42238.481141,-5131.398865,-1335.388327,1542.125218,-2150.267561,-250.648161,114.473620,-336.176614,324.724203,581.168354,...,17.121076,37.491441,-35.314305,14.871012,44.154356,-152.921040,114.661306,309.145761,-270.284829,0

In [68]:
x_test.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,144783.386368,-12584.618022,-315.633695,-6116.649754,-954.643084,-1566.976296,1862.582414,944.567996,-2335.952421,-241.511273,...,-159.903665,1005.437187,-545.552981,-19.580925,84.401909,-124.618428,-97.944304,-52.751828,408.389763,-320.441290
1,-42236.006319,-5130.146565,-1381.182131,4025.808527,-2322.465907,-246.781151,186.968739,-284.891056,232.452986,630.736097,...,-88.999617,-85.007824,-14.758778,-18.574637,-38.138027,-152.242606,-512.243742,20.845485,-313.011405,481.661775
2,-42215.207833,-5122.770319,-1230.532222,8350.943294,-2287.325167,-34.521689,589.924286,505.548325,-757.528465,-217.721706,...,48.409117,0.150346,-59.695443,10.885849,-9.366003,34.145710,78.408627,-32.850161,12.471432,-62.297277
3,-42240.112871,-5133.177236,-1087.593655,1336.979657,-2240.345942,-114.948668,230.951064,-120.089676,372.977117,610.138133,...,65.918849,135.185759,27.778510,-68.348808,-128.685338,47.735614,23.231337,-50.738360,22.679799,-144.642111
4,-42234.573712,-5127.148887,-1224.250626,-4242.992929,-1463.982515,-255.541976,77.222632,-356.853249,205.065643,538.691712,...,-118.852296,-81.500208,-76.765853,87.461237,73.960421,-24.012812,-350.659104,19.100080,176.718062,-218.229900

In [70]:
train.to_csv('transaction.csv', index=False)
x_test.to_csv('transaction_test.csv', index=False)